### ISSUE TITLE
Wiki pages

### ISSUE THREAD

**Issue by Smyja** [fylein/qbo-sdk-py#21]
Hey, i've been trying to find the wiki pages for the project or a documentation link.

**Comment by Shwetabhk** [comment]
Hey @Smyja,
Sorry, we don't have a wiki at the moment but the usage is very straightforward. You can check the readme to started https://github.com/fylein/qbo-sdk-py/blob/master/README.md and let me know in case you face any issues!

**Comment by Smyja** [comment]
> Hey @Smyja,
> Sorry, we don't have a wiki at the moment but the usage is very straightforward. You can check the readme to started https://github.com/fylein/qbo-sdk-py/blob/master/README.md and let me know in case you face any issues!

Yeah, I checked the code.
